### PR TITLE
Set leading and trailing constraints relative to superview

### PR DESCRIPTION
**Pull request by Shiaulis**
Before
image

After
image

### CODE REVIEW

**Review by alexnivanov — CHANGES_REQUESTED** [review]
Great! But please do the same for the buttons on the left. They have more padding than required on the second screen.

**Comment by Shiaulis** [comment]
> Great! But please do the same for the buttons on the left. They have more padding than required on the second screen.

Sure. Will do in a while

**Comment by alexnivanov** [comment]
Cool, waiting :)

**Comment by Shiaulis** [comment]
@alexnivanov , is there any way to reach you in any messenger? Telegram?

**Comment by Shiaulis** [comment]
> Great! But please do the same for the buttons on the left. They have more padding than required on the second screen.

image
Actually, it looks like these constraints do not need to be updated. They will be too close to safe area in that case

**Comment by Shiaulis** [comment]
The safe area at the bottom of the screen is needed for swipe actions

**Comment by alexnivanov** [comment]
@Shiaulis yeah true! Regarding contact, we are going to enable Gitter soon, meanwhile you can indeed contact me in Telegram, @alexnivanov :)

**Pull request merged**
